version: '3.1'

services:
    bantucms-php-apache:
        build:
            args:
                container_project_path: /var/www/html/
                uid: 1428
                user: $USER
            context: .
            dockerfile: ./Dockerfile
        image: bantucms-php-apache
        ports:
            - 80:80
        volumes:
            - ./workspace/:/var/www/html/

    bantucms-mysql:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_HOST: '%'
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3306:3306
        volumes:
            - ./.configs/mysql-data:/var/lib/mysql/

    bantucms-phpmyadmin:
        image: phpmyadmin:latest
        restart: always
        environment:
            PMA_HOST: bantucms-mysql
            PMA_USER: root
            PMA_PASSWORD: root
        ports:
            - 8080:80